// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_release from "./routes/api/release.ts";
import * as $draft from "./routes/draft.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DraftTool from "./islands/DraftTool.tsx";
import * as $ReleaseButton from "./islands/ReleaseButton.tsx";
import * as $SyncButton from "./islands/SyncButton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/release.ts": $api_release,
    "./routes/draft.tsx": $draft,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/DraftTool.tsx": $DraftTool,
    "./islands/ReleaseButton.tsx": $ReleaseButton,
    "./islands/SyncButton.tsx": $SyncButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
