// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin from "./routes/admin.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_register from "./routes/api/register.ts";
import * as $api_release from "./routes/api/release.ts";
import * as $api_sync_banzuke from "./routes/api/sync-banzuke.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $reg_complete from "./routes/reg_complete.tsx";
import * as $register from "./routes/register.tsx";
import * as $rikishi from "./routes/rikishi.tsx";
import * as $stable from "./routes/stable.tsx";
import * as $test_page from "./routes/test_page.tsx";
import * as $BanzukeSync from "./islands/BanzukeSync.tsx";
import * as $DraftTool from "./islands/DraftTool.tsx";
import * as $ReleaseButton from "./islands/ReleaseButton.tsx";
import * as $SpoilerShield from "./islands/SpoilerShield.tsx";
import * as $SyncButton from "./islands/SyncButton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin.tsx": $admin,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/register.ts": $api_register,
    "./routes/api/release.ts": $api_release,
    "./routes/api/sync-banzuke.ts": $api_sync_banzuke,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/reg_complete.tsx": $reg_complete,
    "./routes/register.tsx": $register,
    "./routes/rikishi.tsx": $rikishi,
    "./routes/stable.tsx": $stable,
    "./routes/test_page.tsx": $test_page,
  },
  islands: {
    "./islands/BanzukeSync.tsx": $BanzukeSync,
    "./islands/DraftTool.tsx": $DraftTool,
    "./islands/ReleaseButton.tsx": $ReleaseButton,
    "./islands/SpoilerShield.tsx": $SpoilerShield,
    "./islands/SyncButton.tsx": $SyncButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
